[package]
name = "evaluation"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
keyword_search = { path = "../keyword_search" }
simplepir = { path = "../simplepir" }
postgres = "0.19"
criterion = { version = "0.5", features = ["csv_output"] }
ndarray = "0.16"
rand = "0.8"
rayon = "1.10"

[[bench]]
name = "querying"
path = "benches/querying.rs"
harness = false

[[bench]]
name = "offline_setup"
path = "benches/offline_setup.rs"
harness = false

[[bench]]
name = "auxiliary"
path = "benches/auxiliary.rs"
harness = false

[[bench]]
name = "multiple_query"
path = "benches/multiple_query.rs"
harness = false

[[bench]]
name = "parallel_multiple_query"
path = "benches/parallel_multiple_query.rs"
harness = false

[[bench]]
name = "keyword_search"
path = "benches/keyword_search.rs"
harness = false

[[bench]]
name = "batching_vars"
path = "benches/batching_vars.rs"
harness = false

[[bench]]
name = "bucket_padding"
path = "benches/bucket_padding.rs"
harness = false
