version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pir_db
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data  
      - postgres_data:/var/lib/postgresql/data

  server: 
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/pir_db
    depends_on:
      - db
volumes:
  postgres_data: